"""empty message

Revision ID: 0a70218b8dda
Revises: 
Create Date: 2019-08-27 21:52:38.438942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a70218b8dda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disease_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disease_name', sa.String(length=200), nullable=True),
    sa.Column('disease_signs', sa.String(length=2000), nullable=True),
    sa.Column('disease_symptoms', sa.String(length=2000), nullable=True),
    sa.Column('confirmatory_tests', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disease_data')
    # ### end Alembic commands ###
